name: GitHub Actions
run-name: Run tests.
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest



#https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python